Fix issue with changing maxTrackPoints down by less than half
restrictPoints sets the size through restrictPoints then we grab the first maxPoints and slice the array
so _size was set to a value larger than the new array size

---
Error: Array Out Of Bounds Error
Details: 'Failed invoking <symbol>'
Time: 2025-11-09T05:34:32Z
Part-Number: 006-B3704-00
Firmware-Version: '19.05'
Language-Code: eng
ConnectIQ-Version: 5.2.0
Filename: 'optimized-ULBreadcrumbDataField'
Appname: ULBreadcrumbDataField
Stack:
  - pc: 0x10003631
    File: 'C:\Users\RandomGuy2.1\garmin_apps\ULBreadcrumbDataField\source\PointArray.mc'
    Line: 192
    Function: getPoint
  - pc: 0x100036e3
    File: 'C:\Users\RandomGuy2.1\garmin_apps\ULBreadcrumbDataField\source\PointArray.mc'
    Line: 175
    Function: lastPoint
  - pc: 0x100038b2
    File: 'C:\Users\RandomGuy2.1\garmin_apps\ULBreadcrumbDataField\source\CachedValues.mc'
    Line: 107
    Function: getNewScaleAndUpdateCenter
  - pc: 0x10003dc6
    File: 'C:\Users\RandomGuy2.1\garmin_apps\ULBreadcrumbDataField\source\CachedValues.mc'
    Line: 92
    Function: updateScaleCenter
  - pc: 0x10003b17
    File: 'C:\Users\RandomGuy2.1\garmin_apps\ULBreadcrumbDataField\source\CachedValues.mc'
    Line: 272
    Function: recalculateAll
  - pc: 0x10001702
    File: 'C:\Users\RandomGuy2.1\garmin_apps\ULBreadcrumbDataField\source\Settings.mc'
    Line: 164
    Function: updateCachedValues
  - pc: 0x1000138e
    File: 'C:\Users\RandomGuy2.1\garmin_apps\ULBreadcrumbDataField\source\Settings.mc'
    Line: 72
    Function: setValueSideEffect
  - pc: 0x1000163a
    File: 'C:\Users\RandomGuy2.1\garmin_apps\ULBreadcrumbDataField\source\Settings.mc'
    Line: 68
    Function: setValue
  - pc: 0x10001695
    File: 'C:\Users\RandomGuy2.1\garmin_apps\ULBreadcrumbDataField\source\Settings.mc'
    Line: 99
    Function: setMaxTrackPoints
  - pc: 0x10003f1b
    File: 'C:\Users\RandomGuy2.1\garmin_apps\ULBreadcrumbDataField\source\NumberPicker.mc'
    Line: 252
    Function: onReading
  - pc: 0x10001a86
    File: 'C:\Users\RandomGuy2.1\garmin_apps\ULBreadcrumbDataField\source\NumberPicker.mc'
    Line: 113
    Function: tryComplete
  - pc: 0x1000193f
    File: 'C:\Users\RandomGuy2.1\garmin_apps\ULBreadcrumbDataField\source\NumberPicker.mc'
    Line: 167
    Function: onTap
  - pc: 0x10003e90
    File: 'C:\Users\RandomGuy2.1\garmin_apps\ULBreadcrumbDataField\source\NumberPicker.mc'
    Line: 331
    Function: onTap
  - pc: 0x30002e93
  - pc: 0x30003dcf